# fly.toml file generated for cartracker on 2023-03-06T21:15:19-06:00

app = "cartracker"
kill_signal = "SIGINT"
kill_timeout = 5

[env]

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 5000
  processes = ["app"]
  protocol = "tcp"
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true 

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.ports.http_options]
    idle_timeout = 30

  [service.concurrency]
    hard_limit = 5
    soft_limit = 3
    type = "connections"